import { describe, it, expect } from 'vitest';
import {
  ALL_TOPIC_SLUGS,
  TOPIC_NAMES,
  TOPIC_COUNT,
  TOPIC_ORDER,
  translateTopic,
} from './topics';

describe('topics translation', () => {
  it('has 30+ topics defined', () => {
    // Sanity: if this drops, someone removed topics. We keep
    // 30+ as a soft floor because the unified taxonomy merged
    // some of the kazcorpus sections together.
    expect(TOPIC_COUNT).toBeGreaterThanOrEqual(30);
  });

  it('every topic has non-empty RU and KZ display names', () => {
    for (const slug of ALL_TOPIC_SLUGS) {
      const t = TOPIC_NAMES[slug];
      expect(t, `missing topic "${slug}"`).toBeDefined();
      expect(t.ru.length, `empty ru for "${slug}"`).toBeGreaterThan(0);
      expect(t.kz.length, `empty kz for "${slug}"`).toBeGreaterThan(0);
    }
  });

  it('RU and KZ names differ for every topic', () => {
    for (const slug of ALL_TOPIC_SLUGS) {
      const t = TOPIC_NAMES[slug];
      expect(t.ru === t.kz, `ru equals kz for "${slug}"`).toBe(false);
    }
  });

  it('translateTopic returns "RU / KZ" pair', () => {
    for (const slug of ALL_TOPIC_SLUGS) {
      const label = translateTopic(slug, 'ru');
      const t = TOPIC_NAMES[slug];
      expect(label, `wrong format for "${slug}"`).toBe(`${t.ru} / ${t.kz}`);
    }
  });

  it('falls back to the input for unknown slugs', () => {
    expect(translateTopic('not-a-real-slug', 'ru')).toBe('not-a-real-slug');
    expect(translateTopic('', 'ru')).toBe('');
  });
});

describe('unified topic taxonomy', () => {
  // The taxonomy is generated by `scripts/unify-topics.mjs`. We assert
  // the on-disk taxonomy is internally consistent: every slug is
  // unique, the order array matches the keys, and the canonical
  // family groups are all present.
  it('every slug is unique', () => {
    const seen = new Set<string>();
    for (const slug of ALL_TOPIC_SLUGS) {
      expect(seen.has(slug), `duplicate slug "${slug}"`).toBe(false);
      seen.add(slug);
    }
  });

  it('TOPIC_ORDER matches ALL_TOPIC_SLUGS', () => {
    expect([...TOPIC_ORDER].sort()).toEqual([...ALL_TOPIC_SLUGS].sort());
  });

  it('contains the canonical CEFR family groups', () => {
    const required = [
      'greetings',
      'family',
      'home',
      'work',
      'food',
      'weather',
      'clothes',
      'health',
      'holidays',
      'appearance',
      'time',
      'travel',
      'education',
      'media',
      'negation',
    ];
    const set = new Set(ALL_TOPIC_SLUGS);
    for (const r of required) {
      expect(set.has(r), `missing canonical topic "${r}"`).toBe(true);
    }
  });
});
