/**
 * Unified topic taxonomy.
 *
 * Generated by `scripts/unify-topics.mjs` from the canonical
 * topic list at the top of that file. Do not edit by hand —
 * re-run the script to refresh.
 *
 * Each entry pairs a Russian display name with a Kazakh one so
 * the UI can render "<Название на русском> / <Название на казахском>"
 * (per project requirement) without going through i18n tables.
 */

/** A canonical topic: { ru, kz } display names. */
export interface TopicName {
  /** Russian display name (used in the UI as the primary label). */
  ru: string;
  /** Kazakh display name (used in the UI as the secondary label). */
  kz: string;
}

/**
 * Slug → { ru, kz }. Stable, in canonical order. The slugs are the
 * exact strings stored in `Card.category` in
 * `src/data/decks/*.json`.
 */
export const TOPIC_NAMES: Readonly<Record<string, TopicName>> = Object.freeze({
  greetings: { ru: "Приветствия и этикет", kz: "Сәлемдесу және сыпайылық" },
  family: { ru: "Семья и родственники", kz: "Отбасы және туыстар" },
  home: { ru: "Дом и быт", kz: "Үй және тұрмыс" },
  work: { ru: "Работа и профессии", kz: "Жұмыс және мамандық" },
  food: { ru: "Еда и напитки", kz: "Тамақ және сусындар" },
  leisure: { ru: "Досуг и хобби", kz: "Бос уақыт және хобби" },
  weather: { ru: "Погода и природа", kz: "Ауа-райы және табиғат" },
  clothes: { ru: "Одежда и мода", kz: "Киім және сән" },
  health: { ru: "Здоровье", kz: "Денсаулық" },
  holidays: { ru: "Праздники и традиции", kz: "Мерекелер және дәстүрлер" },
  appearance: { ru: "Внешность", kz: "Сыртқы келбет" },
  buildings: { ru: "Здания и места", kz: "Ғимараттар және орындар" },
  time: { ru: "Время и календарь", kz: "Уақыт және күнтізбе" },
  names: { ru: "Имена и личные данные", kz: "Есімдер және жеке деректер" },
  country: { ru: "Моя страна", kz: "Менің елім" },
  plants: { ru: "Растения и животные", kz: "Өсімдіктер және жануарлар" },
  services: { ru: "Услуги и покупки", kz: "Қызметтер және сатып алу" },
  documents: { ru: "Документы", kz: "Құжаттар" },
  communication: { ru: "Общение и речь", kz: "Қарым-қатынас және сөйлеу" },
  media: { ru: "СМИ и медиа", kz: "БАҚ және медиа" },
  lifestyle: { ru: "Образ жизни", kz: "Өмір салты" },
  travel: { ru: "Путешествия", kz: "Саяхат" },
  world: { ru: "Мир и общество", kz: "Әлем және қоғам" },
  education: { ru: "Образование", kz: "Білім" },
  desire: { ru: "Желание и намерение", kz: "Ықылас және ниет" },
  information: { ru: "Информация и сообщение", kz: "Ақпарат және хабарлау" },
  negation: { ru: "Отрицание", kz: "Жоққа шығару" },
  continuation: { ru: "Продолжение и связность", kz: "Жалғастыру" },
  pronouns: { ru: "Местоимения", kz: "Есімдіктер" },
  evaluation: { ru: "Оценка", kz: "Бағалау" },
  crime: { ru: "Преступление", kz: "Қылмыс" },
  waste: { ru: "Отходы", kz: "Қалдықтар" },
  antipathy: { ru: "Антипатия и неприязнь", kz: "Жек көру" },
  adjectives: { ru: "Одинаковые прилагательные", kz: "Бірдей сын есімдер" },
});

/** Slugs in canonical order (matches `TOPICS` in the generator). */
export const TOPIC_ORDER: ReadonlyArray<string> = Object.freeze([
  "greetings",
  "family",
  "home",
  "work",
  "food",
  "leisure",
  "weather",
  "clothes",
  "health",
  "holidays",
  "appearance",
  "buildings",
  "time",
  "names",
  "country",
  "plants",
  "services",
  "documents",
  "communication",
  "media",
  "lifestyle",
  "travel",
  "world",
  "education",
  "desire",
  "information",
  "negation",
  "continuation",
  "pronouns",
  "evaluation",
  "crime",
  "waste",
  "antipathy",
  "adjectives",
]);

/** Number of canonical topics. */
export const TOPIC_COUNT: number = 34;

/**
 * Resolve a slug to a display label. Returns "RU / KZ" by default.
 * Unknown slugs fall back to the slug itself so the UI never blanks.
 *
 * The `lang` parameter is preserved for forward-compat — the app
 * is Russian-only today but the same shape works for any future
 * locale.
 */
export function translateTopic(slug: string, _lang: 'ru' | 'en' = 'ru'): string {
  if (!slug) return '';
  const t = TOPIC_NAMES[slug];
  if (!t) return slug;
  return t.ru + ' / ' + t.kz;
}

/** All canonical slugs in order. Useful for tests / iteration. */
export const ALL_TOPIC_SLUGS: ReadonlyArray<string> = TOPIC_ORDER;
